#!/bin/bash
set -e
masterBranch="master"

((!$#)) && echo No feature name, command ignored! && echo "  - git feature <name> <startingPoint>" && exit 1

if [[ "$1" = "--h" ]] ; then
   echo "Creates a feature branch at either the latest commit on $masterBranch or when supplied the <startingPoint> and checks it out.";
   echo "Feature branches will create a pull request to $masterBranch when finished."
   echo "  - git feature <name> <startingPoint>";
   exit 1;
fi

if ! [ -d .git ] ; then
	if ! [ $(git rev-parse --is-inside-work-tree &>/dev/null; echo "${?}") == '0' ] ; then
		echo "Current directory is not a git folder."
		exit 1;
	fi
fi

head=$masterBranch
if [ "$2" = "" ]; then
	echo branching from latest commit on $head
else
	head=$2
	echo branching from requested starting point: $head
fi

echo Starting feature $1
git checkout -b feature/$1 $head
# create remote origin for the local branch
git push --set-upstream origin feature/$1