#!/bin/bash
set -e
masterBranch="master"

if [[ "$1" = "--h" ]] ; then
   echo "Finishing up feature and issue branches: ";
   echo "  - git finish";
   echo ""
   echo "Finishing up release and hotfix branches: ";
   echo "  - git finish <annotation>";
   echo	"    where annotation is optional";
   exit 1;
fi

if ! [ -d .git ] ; then
	if ! [ $(git rev-parse --is-inside-work-tree &>/dev/null; echo "${?}") == '0' ] ; then
		echo "Current directory is not a git folder."
		exit 1;
	fi
fi

branch=$(git rev-parse --abbrev-ref HEAD)
shortBranch=$(echo $branch| cut -d'/' -f 2)

create_pullrequest () {
originUrl=$(git config --get remote.origin.url)

case $( uname -s ) in
  Darwin)  open='open';;
  MINGW*)  open='start';;
  MSYS*)   open='start';;
  CYGWIN*) open='cygstart';;
  *)       open='xdg-open';;
esac

# Allow printing the url if BROWSER=echo
if [[ $BROWSER != "echo" ]]; then
  exec &>/dev/null
fi

# open it in a browser
${BROWSER:-$open} "$originUrl"

}

if [[ $branch =~ ^(feature|issue).* ]]; then
    echo Pulling latest $masterBranch from origin
	git pull origin $masterBranch:$masterBranch
	
    echo Merging $masterBranch into local branch
  git merge $masterBranch		
elif [[ $branch =~ ^(release|hotfix).* ]]; then
    echo Tagging release branch
	
	if [ "$1" = "" ]; then
		git tag V$shortBranch
	else
		git tag -a V$shortBranch -m "$1"
	fi	
else 
	echo "Currently not on a feature/issue/release/hotfix branch";
	exit 1;
fi

# We should never merge into master from this script -> we can instead use github to do it manually
# Here should just always create a pull request. 
echo "Create a pull request"
create_pullrequest $branch; exit 0;
