#!/bin/bash
set -e
masterBranch="master"

if [[ "$1" = "--h" ]] ; then
   echo "Finishing up feature and issue branches: ";
   echo "  - git finish";
   echo ""
   echo "Finishing up release and hotfix branches: ";
   echo "  - git finish <annotation>";
   echo	"    where annotation is optional";
   exit 1;
fi

if ! [ -d .git ] ; then
	if ! [ $(git rev-parse --is-inside-work-tree &>/dev/null; echo "${?}") == '0' ] ; then
		echo "Current directory is not a git folder."
		exit 1;
	fi
fi

branch=$(git rev-parse --abbrev-ref HEAD)
shortBranch=$(echo $branch| cut -d'/' -f 2)

if [[ $branch =~ ^(feature|issue).* ]]; then
	# TODO: do something to finish the branch
elif [[ $branch =~ ^(release|hotfix).* ]]; then
    echo Tagging release branch
	
	if [ "$1" = "" ]; then
		git tag V$shortBranch
	else
		git tag -a V$shortBranch -m "$1"
	fi	
else 
	echo "Currently not on a feature/issue/release/hotfix branch";
	exit 1;
fi